name: cow_detection

channels:
- conda-forge
- anaconda 

dependencies:
# Essential
- python==3.7.6
- pip==19.3.1
# Data Science
- numpy==1.18.1

- pip:
  # Computer Vision
  - opencv-python==4.2.0.34
  - jcopvision